### PR TITLE
Backport to Java 8

### PR DESCRIPTION
**Pull request by zeitlinger**
These are just the code changes - please advise how to adjust the release process.

To be merged after #100

### CODE REVIEW

**Comment by vadeg** [comment]
This will not build properly unless security issues appeared in #100 will be resolved and backported here. Or we should make a release without security checks and disabling CVE plugin which I am not in favor of.

**Comment by vadeg** [comment]
Since Java 8 libraries will work in Java 11 I think the simplest solution will be to backport the source code to Java 8 only for this release and then release it again with Java 11. Otherwise we would need to build a parallel Java 8 build with a separate branch only for one specific release.

**Comment by zeitlinger** [comment]
> This will not build properly unless security issues appeared in #100 will be resolved and backported here. Or we should make a release without security checks and disabling CVE plugin which I am not in favor of.

This PR should be merged after #100

**Comment by zeitlinger** [comment]
> Since Java 8 libraries will work in Java 11 I think the simplest solution will be to backport the source code to Java 8 only for this release and then release it again with Java 11. Otherwise we would need to build a parallel Java 8 build with a separate branch only for one specific release.

sounds good to me

**Comment by vadeg** [comment]
Superseded by #102

**Pull request closed without merging**
